package org.ricky.admin.api.pojo;

import java.io.Serializable;

public class UserPo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5690056410306652876L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.id
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.user_name
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.password
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_t.role
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	private Integer role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.id
	 * @return  the value of user_t.id
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.id
	 * @param id  the value for user_t.id
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.user_name
	 * @return  the value of user_t.user_name
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.user_name
	 * @param userName  the value for user_t.user_name
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.password
	 * @return  the value of user_t.password
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.password
	 * @param password  the value for user_t.password
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_t.role
	 * @return  the value of user_t.role
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_t.role
	 * @param role  the value for user_t.role
	 * @mbggenerated  Wed Sep 09 14:18:08 CST 2015
	 */
	public void setRole(Integer role) {
		this.role = role;
	}
}